#!/bin/sh

# qemundo: easy virtual machine manager for QEMU
#
# Usage: qemundo COMMAND [OPTIONS]
#
#   install <path>          Create a new virtual machine.
#     -a/--arch <arch>      Emulate this architecture. (arm64)
#     -o/--os <os>          Install this operating system. (netbsd-9)
#     -s/--size <size>      The size of the disk image. (5G)
#     -m/--memory <memory>  The amount of memory to allocate. (512M)
#     -p/--cpus <size>      The number of processors. (8)
#
#   list                    Print supported build targets.
#   help                    Print this help message and exit.
#
# Pull requests are welcome! https://github.com/elijahr/qemundo
#
# Copyright (c) 2020 Elijah Shaw-Rutschman
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

VERSION="1.0.0"

ME=`basename "$0"`
DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
HOST=`uname -a`

DEFAULT_OS=netbsd-9
DEFAULT_ARCH=arm64
DEFAULT_SIZE=5G
DEFAULT_MEMORY=512M
DEFAULT_CPUS=`nproc`

install () {
  if [ -d "${BUILD}" ]; then
    read -p "Existing machine in ${BUILD} will be overwritten. Are you sure? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      fail "Cancelled by user."
    fi
  else
    test -f "${BUILD}" && fail "${BUILD} is a file, expected directory"
  fi
  NAME="$(basename "${BUILD}")"
  echo "Creating virtual machine ${NAME}"

  # Ensure qemu-system-aarch64 is installed
  if ! command -v qemu-system-aarch64 &> /dev/null
  then
    case $HOST in
      *ubuntu* | *debian* )
        apt-get update
        apt-get install qemu-system-arm qemu-efi-aarch64 qemu-utils
        ;;
      *Darwin* )
        brew install qemu coreutils
        ;;
      * )
        fail "qemu-system-aarch64 not found. Install qemu first."
        ;;
    esac
  fi

  test -d "${BUILD}" && rm "${BUILD}/"*
  mkdir -p "${BUILD}"

  case $ARCH in
    arm64 )
      case $OS in
        ubuntu-bionic )
          SHA256=015c2e34cc950b78682b772e9197164a144a565e112660d1183825ead80005cc
          ISO=http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/main/installer-arm64/current/images/netboot/mini.iso
          CPU=max
          MACHINE=virt,gic-version=max
          ;;
        netbsd-9 )
          SHA256=81db6afa511d4ec32883379525019e2762535ecac85c044262e40525bc1a47d7
          GZIMG=http://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-9/latest/evbarm-aarch64/binary/gzimg/arm64.img.gz
          CPU=cortex-a53
          MACHINE=virt
          ;;
        * )
          echo "Unsupported operating system ${OS}"
          fail "Pull requests welcome at https://github.com/elijahr/qemundo"
          ;;
      esac

      # Ensure firmware exists
      EFI="${BUILD}/edk2-aarch64-code.fd"
      case $HOST in
        *ubuntu* | *debian* )
          cp /usr/share/qemu-efi-aarch64/QEMU_EFI.fd "${EFI}"
          ;;
        *Darwin* )
          cp /usr/local/opt/qemu/share/qemu/edk2-aarch64-code.fd "${EFI}"
          ;;
        * )
          echo "Fetching firmware..."
          cd ${BUILD}
          curl https://raw.githubusercontent.com/qemu/qemu/3284aa128153750f14a61e8a96fd085e6f2999b6/pc-bios/edk2-aarch64-code.fd.bz2 -LSsf > edk2-aarch64-code.fd.bz2
          bunzip2 edk2-aarch64-code.fd.bz2
          SUM=`sha256 "${BUILD}/edk2-aarch64-code.fd" | cut -f1 -d " "`
          test "${SUM}" == "f9755860bce37ea5a4588f541e5b98fff1bcaff3fc89d272483265fb40e46958" || fail "edk2-aarch64-code.fd checksum did not match"
          ;;
      esac

      echo "Copying firmware image..."
      dd if=/dev/zero of="${BUILD}/pflash.img" bs=1048576 count=64 >/dev/null 2>&1
      dd if="${EFI}" of="${BUILD}/pflash.img" conv=notrunc >/dev/null 2>&1
      rm "${EFI}"

      if [ "${ISO}" != "" ]; then
        echo "Creating blank ${SIZE} disk image..."
        qemu-img create -f raw "${BUILD}/drive0.img" "${SIZE}" >/dev/null 2>&1

        echo "Fetching ${OS} install ISO..."
        curl "${ISO}" -LsSf > "${BUILD}/install.iso"

        echo "Verifying install ISO..."
        SUM=`sha256sum "${BUILD}/install.iso" | cut -f1 -d " "`
        test "${SUM}" == "${SHA256}" || fail "ISO checksum did not match: '${SUM}' != '${SHA256}'"

        echo "Booting installer..."
        qemu-system-aarch64 \
          -nographic \
          -machine "${MACHINE}" \
          -m "${MEMORY}" \
          -cpu "${CPU}" \
          -smp "${CPUS}" \
          -netdev user,id=vnet,hostfwd=:127.0.0.1:0-:22 \
          -device virtio-net-pci,netdev=vnet \
          -drive file="${BUILD}/drive0.img,if=none,id=drive0,cache=writeback" \
          -device virtio-blk,drive=drive0,bootindex=0 \
          -drive file="${BUILD}/install.iso,if=none,id=drive1,cache=writeback" \
          -device virtio-blk,drive=drive1,bootindex=1 \
          -drive file="${BUILD}/pflash.img,format=raw,if=pflash"

        rm "${BUILD}/install.iso"
      else
        if [ "${GZIMG}" != "" ]; then
          echo "Fetching ${OS} image..."
          curl "${GZIMG}" -LsSf > "${BUILD}/drive0.img.gz"
          echo "Verifying image..."
          SUM=`sha256sum "${BUILD}/drive0.img.gz" | cut -f1 -d " "`
          test "${SUM}" == "${SHA256}" || fail "Image checksum did not match: '${SUM}' != '${SHA256}'"
          cd "${BUILD}"
          gunzip drive0.img.gz
          echo "Resizing image to ${SIZE}..."
          qemu-img resize -f raw "${BUILD}/drive0.img" "${SIZE}"
        else
          fail "Bug in script: no image or ISO to download."
        fi
      fi
      touch "${BUILD}/run.sh"
      chmod +x "${BUILD}/run.sh"
      cat <<EOF > "${BUILD}/run.sh"
#!/bin/sh

CPU="${CPU}"
CPUS="${CPUS}"
MEMORY="${MEMORY}"

DIR="\$( cd "\$(dirname "\$0")" >/dev/null 2>&1 ; pwd -P )"

qemu-system-aarch64 \\
  -nographic \\
  -machine ${MACHINE} \\
  -m "\${MEMORY}" \\
  -cpu "\${CPU}" \\
  -smp "\${CPUS}" \\
  -netdev user,id=vnet,hostfwd=:127.0.0.1:0-:22 \\
  -device virtio-net-pci,netdev=vnet \\
  -drive file="\${DIR}/drive0.img,if=none,id=drive0,cache=writeback" \\
  -device virtio-blk,drive=drive0,bootindex=0 \\
  -drive file="\${DIR}/pflash.img,format=raw,if=pflash"
EOF
      ;;
    * )
      echo "Unsupported architecture ${ARCH}"
      fail "Pull requests welcome at https://github.com/elijahr/qemundo"
      ;;
  esac
}

usage () {
  echo
  echo "Usage: ${ME} COMMAND [OPTIONS]"
  echo
  echo "  install <path>          Create a new virtual machine at path (default: <os>-<arch>).."
  echo "    -o/--os <os>          Install this operating system. (default: ${DEFAULT_OS})"
  echo "    -a/--arch <arch>      Emulate this architecture. (default: ${DEFAULT_ARCH})"
  echo "    -s/--size <size>      The size of the disk image. (default: ${DEFAULT_SIZE})"
  echo "    -m/--memory <memory>  The amount of memory to allocate. (default: ${DEFAULT_MEMORY})"
  echo "    -p/--cpus <size>      The number of processors. (default: ${DEFAULT_CPUS})"
  echo
  echo "  list                    Print supported build targets and exit."
  echo "  help                    Print this help message and exit."
  echo
}

parse_install_args () {
  POSITIONAL=()
  while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
      -a|--arch)
        ARCH="$2"; shift; shift;
        ;;
      -o|--os)
        OS="$2"; shift; shift;
        ;;
      -s|--size)
        SIZE="$2"; shift; shift;
        ;;
      -m|--memory)
        MEMORY="$2"; shift; shift;
        ;;
      -p|--cpus)
        CPUS="$2"; shift; shift;
        ;;
      -*)
        echo "Unknown option for install: $key"
        usage
        exit 1
        ;;
      *)
        POSITIONAL+=("$1"); shift;
        ;;
    esac
  done

  if [[ "${ARCH}" == "" ]]; then
    ARCH=${DEFAULT_ARCH}
  fi
  if [[ "${OS}" == "" ]]; then
    OS=${DEFAULT_OS}
  fi
  if [[ "${SIZE}" == "" ]]; then
    SIZE=${DEFAULT_SIZE}
  fi
  if [[ "${MEMORY}" == "" ]]; then
    MEMORY=${DEFAULT_MEMORY}
  fi
  if [[ "${CPUS}" == "" ]]; then
    CPUS=${DEFAULT_CPUS}
  fi

  test ${#POSITIONAL[@]} -lt 2 || fail "install takes a single positional <path> argument, got ${#POSITIONAL[@]}."

  if [ "${POSITIONAL[0]}" == "" ]; then
    BUILD=`realpath "${OS}-${ARCH}"`
  else
    BUILD=`realpath "${POSITIONAL[0]}"`
  fi
}

main () {
  args=($@)
  cmd=${args[0]}
  case $cmd in
    install )
      parse_install_args "${args[@]:1}"
      install
      echo
      echo "Installed image in ${BUILD}"
      echo "Run this image with:"
      echo
      echo "sh \"${BUILD}/run.sh\""
      echo
      ;;
    list )
      echo
      echo "Supported targets:"
      echo
      echo "  --arch arm64 --os ubuntu-bionic"
      echo "  --arch arm64 --os netbsd-9"
      echo
      ;;
    help )
      echo "qemundo: easy virtual machine manager for QEMU (v${VERSION})"
      usage
      ;;
    * )
      echo "Unknown command ${cmd}"
      usage
      exit 1
      ;;
  esac
}

fail () {
  echo $1
  exit 1
}

main $@