#!/bin/sh

# qemundo: easy virtual machine manager for QEMU
#
# Usage: qemundo COMMAND [OPTIONS]
#
#   install [path]          Create a new virtual machine at path (default: <os>-<arch>)..
#     -o/--os <os>          Install this operating system (default: ubuntu-bionic)
#     -a/--arch <arch>      Emulate this architecture (default: arm64)
#     -s/--size <size>      The size of the disk image (default: 5G)
#     -m/--memory <memory>  The amount of memory to allocate (default: 512M)
#     -p/--cpus <count>     The number of processors (default: output of nproc)
#
#   clean                   Remove all cached ISOs and images
#   list                    Print supported build targets and exit
#   help                    Print this help message and exit
#
# Copyright (c) 2020 Elijah Shaw-Rutschman
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

ME=`basename "$0"`
DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
HOST=`uname -a`
CACHE="${HOME}/.cache/qemundo"

DEFAULT_OS=ubuntu-bionic
DEFAULT_ARCH=arm64
DEFAULT_SIZE=5G
DEFAULT_MEMORY=512M
DEFAULT_CPUS=`nproc`

install () {
  CACHED_ISO="${CACHE}/${OS}-${ARCH}.iso"
  CACHED_DISK="${CACHE}/${OS}-${ARCH}.qcow2"
  DISK="${BUILD}/disk.qcow2"
  CACHED_FIRMWARE="${CACHE}/${ARCH}-firmware.qcow2"
  FIRMWARE="${BUILD}/firmware.qcow2"

  case "${ARCH}" in
    arm64 ) prepare_arm64 ;;
    * )
      echo
      echo "Unsupported architecture ${ARCH}"
      supported_guests
      exit 1
      ;;
  esac

  case "${OS}" in
    ubuntu-bionic|alpine-3|netbsd-9 )
      ;;
    * )
      echo
      echo "Unsupported operating system ${OS}"
      supported_guests
      exit 1
      ;;
  esac

  if [ -d "${BUILD}" ]; then
    read -p "Existing machine in ${BUILD} will be overwritten. Are you sure? [y/N] " -n 1 -r
    echo
    if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
      fail "Cancelled by user."
    fi
    rm -R "${BUILD}"
  else
    test -f "${BUILD}" && fail "${BUILD} is a file, expected directory"
  fi

  mkdir -p "${BUILD}"
  mkdir -p "${CACHE}"

  echo "Creating virtual machine at ${BUILD}"

  install_qemu
  copy_firmware
  build_image
  write_run_sh

  echo
  echo "Created VM at ${BUILD}"
  echo "Run this VM with:"
  echo
  echo "sh \"${BUILD}/run.sh\""
  echo
}

install_qemu () {
  # Ensure qemu is installed
  if ! command -v "${QEMU}" &> /dev/null
  then
    case $HOST in
      *ubuntu* | *debian* )
        apt-get update
        # TODO - specific qemu-system-* packages for other architectures
        apt-get install qemu-system-arm qemu-utils
        ;;
      *Darwin* )
        if command -v brew &> /dev/null
        then
          brew install qemu coreutils
        fi
        ;;
    esac
    if ! command -v "${QEMU}" &> /dev/null
    then
      fail "${QEMU} not found. Install qemu."
    fi
  fi
}

copy_firmware () {
  if [ ! -f "${CACHED_FIRMWARE}" ]; then
    if [ "${FIRMWARE_BZ2_URL}" != "" ]; then
      echo "Fetching firmware image ${FIRMWARE_BZ2_URL}..."
      cd ${CACHE}
      curl "${FIRMWARE_BZ2_URL}" -Lf > "${ARCH}-firmware.fd.bz2"
      bunzip2 "${ARCH}-firmware.fd.bz2"
      dd if=/dev/zero of="${ARCH}-firmware.img" bs=1048576 count=64 >/dev/null 2>&1
      dd if="${ARCH}-firmware.fd" of="${ARCH}-firmware.img" conv=notrunc >/dev/null 2>&1
      qemu-img convert -f raw -O qcow2 "${ARCH}-firmware.img" "${CACHED_FIRMWARE}"
      rm "${ARCH}-firmware.fd"
      rm "${ARCH}-firmware.img"
    fi
  fi
  if [ -f "${CACHED_FIRMWARE}" ]; then
    echo "Copying firmware ${CACHED_FIRMWARE}"
    cp "${CACHED_FIRMWARE}" "${FIRMWARE}"
  else
    fail "Bug in qemunod: no firmware"
  fi
}

build_image () {
  if [ "${ISO_URL}" != "" ]; then
    boot_iso
  elif [ "${GZ_IMG_URL}" != "" ]; then
    copy_gz_img
  else
    fail "Bug in qemundo: nothing to download."
  fi
}

boot_iso () {
  if [ ! -f "${CACHED_ISO}" ]; then
    echo "Fetching ISO ${ISO_URL}..."
    mkdir -p ~/.cache/qemundo
    curl "${ISO_URL}" -Lf > "${CACHED_ISO}"
  else
    echo "Using cached ISO ${CACHED_ISO}"
  fi

  echo "Creating disk image ${DISK} (${SIZE})..."
  qemu-img create -f qcow2 "${DISK}" "${SIZE}" >/dev/null 2>&1

  echo "Booting from ISO..."
  sleep 5
  "${QEMU}" \
    -nographic \
    -machine "${MACHINE}" \
    -m "${MEMORY}" \
    -cpu "${CPU}" \
    -smp "${CPUS}" \
    -netdev user,id=vnet,hostfwd=:127.0.0.1:0-:22 \
    -device virtio-net-pci,netdev=vnet \
    -drive file="${DISK},format=qcow2,if=none,id=drive0,cache=writeback" \
    -device virtio-blk,drive=drive0,bootindex=1 \
    -drive file="${CACHED_ISO},format=raw,if=none,id=drive1,cache=writeback" \
    -device virtio-blk,drive=drive1,bootindex=0 \
    -drive file="${FIRMWARE},format=qcow2,if=pflash"
}

copy_gz_img () {
  if [ ! -f "${CACHED_DISK}" ]; then
    echo "Fetching image ${GZ_IMG_URL}..."
    CACHED_RAW="${CACHE}/${OS}-${ARCH}.img"
    curl "${GZ_IMG_URL}" -Lf > "${CACHE}/${OS}-${ARCH}.img.gz"
    gunzip --stdout "${GZ_IMG}" > "${CACHED_RAW}"
    qemu-img convert -f raw -O qcow2 "${CACHED_RAW}" "${CACHED_DISK}"
    rm "${CACHED_RAW}"
    echo "Cached image ${CACHED_DISK}"
  else
    echo "Using cached image ${CACHED_DISK}"
  fi
  echo "Resizing image to ${SIZE}..."
  cp "${CACHED_DISK}" "${DISK}"
  qemu-img resize -f qcow2 "${DISK}" "${SIZE}"
}

prepare_arm64 () {
  QEMU=qemu-system-aarch64
  CPU=max
  MACHINE=virt,gic-version=max
  FIRMWARE_BZ2_URL=https://raw.githubusercontent.com/qemu/qemu/3284aa128153750f14a61e8a96fd085e6f2999b6/pc-bios/edk2-aarch64-code.fd.bz2

  case $OS in
    ubuntu-bionic )
      ISO_URL=http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/main/installer-arm64/current/images/netboot/mini.iso
      ;;
    alpine-3 )
      ISO_URL=http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/aarch64/alpine-standard-3.12.0-aarch64.iso
      ;;
    netbsd-9 )
      GZ_IMG_URL=http://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-9/latest/evbarm-aarch64/binary/gzimg/arm64.img.gz
      CPU=cortex-a53
      MACHINE=virt
      ;;
  esac
}

write_run_sh () {
  touch "${BUILD}/run.sh"
  chmod +x "${BUILD}/run.sh"
  cat <<EOF > "${BUILD}/run.sh"
#!/bin/sh

DIR="\$( cd "\$(dirname "\$0")" >/dev/null 2>&1 ; pwd -P )"

MACHINE="${MACHINE}"
CPU="${CPU}"
CPUS="${CPUS}"
MEMORY="${MEMORY}"
DISK="\${DIR}/disk.qcow2"
FIRMWARE="\${DIR}/firmware.qcow2"

${QEMU} \\
  -nographic \\
  -machine "\${MACHINE}" \\
  -m "\${MEMORY}" \\
  -cpu "\${CPU}" \\
  -smp "\${CPUS}" \\
  -netdev user,id=vnet,hostfwd=:127.0.0.1:0-:22 \\
  -device virtio-net-pci,netdev=vnet \\
  -drive file="\${DISK},format=qcow2,if=none,id=drive0,cache=writeback" \\
  -device virtio-blk,drive=drive0,bootindex=0 \\
  -drive file="\${FIRMWARE},format=qcow2,if=pflash"
EOF
}

usage () {
  echo
  echo "Usage: ${ME} COMMAND [OPTIONS]"
  echo
  echo "  install                 Create a new virtual machine"
  echo "    [path]                Create the VM at this path (default: ./<os>-<arch>)"
  echo "    -o/--os <os>          Install this operating system (default: ${DEFAULT_OS})"
  echo "    -a/--arch <arch>      Emulate this architecture (default: ${DEFAULT_ARCH})"
  echo "    -s/--size <size>      The size of the disk image (default: ${DEFAULT_SIZE})"
  echo "    -m/--memory <memory>  The amount of memory to allocate (default: ${DEFAULT_MEMORY})"
  echo "    -p/--cpus <count>     The number of processors (default: ${DEFAULT_CPUS})"
  echo
  echo "  clean                   Remove all cached ISOs and images"
  echo "  list                    Print supported build targets and exit"
  echo "  help                    Print this help message and exit"
  echo
}

supported_guests () {
  echo
  echo "Supported guests:"
  ech
  echo "  --os ubuntu-bionic   --arch arm64 # Ubuntu Bionic"
  echo "  --os alpine-3        --arch arm64 # Alpine Linux 3"
  echo "  --os netbsd-9        --arch arm64 # NetBSD 9"
  echo
  echo "Pull requests for additional guests are welcome."
  echo "https://github.com/elijahr/qemundo"
  echo
}

parse_install_args () {
  POSITIONAL=()
  while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
      -a|--arch)
        ARCH="$2"; shift; shift;
        ;;
      -o|--os)
        OS="$2"; shift; shift;
        ;;
      -s|--size)
        SIZE="$2"; shift; shift;
        ;;
      -m|--memory)
        MEMORY="$2"; shift; shift;
        ;;
      -p|--cpus)
        CPUS="$2"; shift; shift;
        ;;
      -*)
        echo "Unknown option for install: $key"
        usage
        exit 1
        ;;
      *)
        POSITIONAL+=("$1"); shift;
        ;;
    esac
  done

  if [[ "${ARCH}" == "" ]]; then
    ARCH=${DEFAULT_ARCH}
  fi
  if [[ "${OS}" == "" ]]; then
    OS=${DEFAULT_OS}
  fi
  if [[ "${SIZE}" == "" ]]; then
    SIZE=${DEFAULT_SIZE}
  fi
  if [[ "${MEMORY}" == "" ]]; then
    MEMORY=${DEFAULT_MEMORY}
  fi
  if [[ "${CPUS}" == "" ]]; then
    CPUS=${DEFAULT_CPUS}
  fi

  test ${#POSITIONAL[@]} -lt 2 || fail "install takes a single positional <path> argument, got ${#POSITIONAL[@]}."

  if [ "${POSITIONAL[0]}" == "" ]; then
    BUILD=`realpath "${OS}-${ARCH}"`
  else
    BUILD=`realpath "${POSITIONAL[0]}"`
  fi
}

main () {
  args=($@)
  cmd=${args[0]}
  case $cmd in
    install )
      parse_install_args "${args[@]:1}"
      install
      ;;
    clean )
      if [ -d "${CACHE}" ]; then
        rm -R ${CACHE}
        echo "Removed ${CACHE}"
      fi
      ;;
    list )
      supported_guests
      ;;
    help )
      echo "qemundo: easy virtual machine manager for QEMU"
      usage
      ;;
    * )
      echo "Unknown command ${cmd}"
      usage
      exit 1
      ;;
  esac
}

fail () {
  echo $1
  exit 1
}

main $@